### ISSUE TITLE
Alternative Linking isn't working

### ISSUE THREAD

**Issue by Tux12Fun** [srsp/ansible-oracle-java#13]
Hi

I noticed

`

    - name: alternatives link for "java"
      alternatives:
        name: java
        link: /usr/bin/java
        path: "{{ java_install_dir }}/{{ java_default_link_name }}/bin/java"
`

Is not working on my Ubuntu 18.04. If I change it to this

`

    - name: alternatives link for "java"
      alternatives:
        name: java
        link: /usr/bin/java
        path: "{{ java_install_dir }}/jdk{{ jdk_version }}/bin/java"
`
It's working. - This is not propper for JDK10.

File install.yml

Maybe the Module dosn't create a link on a link?

Tested with jdk8u172 on Ubuntu 18.04 LTS

**Comment by Tux12Fun** [comment]
This is my improved and tested Version of the block.

```yaml
block:
    - name:              Prepare Linkstructure for default-java
      set_fact:
        java_default_link_src:  "{{item.src}}"
        java_default_link_dest: "{{ item.dest}}"
      when: item.when
      with_items:
         - { when: true,                                            src: "{{java_install_dir}}/jdk-{{jdk_version}}",      dest: "{{java_install_dir}}/{{java_default_link_name}}" } # Default JDK 10
         - { when: "{{java_version == 8 and use_rpm == true}}",     src: "{{java_install_dir}}/jdk{{jdk_version}}-amd64", dest: "{{java_install_dir}}/{{java_default_link_name}}" } # JKD8 RPM
         - { when: "{{java_version == 8 and use_tarball == true}}", src: "{{java_install_dir}}/jdk{{jdk_version}}",       dest: "{{java_install_dir}}/{{java_default_link_name}}" } # JDK8 TAR

    - name: Create default-java link
      file:
        src:  "{{java_default_link_src}}"
        dest: "{{java_default_link_dest}}"
        state: link

    - name: check if "java_sdk" target exists
      stat: path=/usr/lib/jvm/java
      register: filecheck

    - name: Creating alternative Links for java executables java, javac, jar, keytool, java_sdk
      alternatives:
         name:  "{{ item.name }}"
         link:  "{{ item.link }}"
         path:  "{{ item.path }}"
      when: item.when
      with_items:
         - { name: "java",     link: "/usr/bin/java",     path: "{{ java_default_link_src }}/bin/java"    , when: true }
         - { name: "javac",    link: "/usr/bin/javac",    path: "{{ java_default_link_src }}/bin/javac"   , when: true }
         - { name: "jar",      link: "/usr/bin/jar",      path: "{{ java_default_link_src }}/bin/jar"     , when: true }
         - { name: "keytool",  link: "/usr/bin/keytool",  path: "{{ java_default_link_src }}/bin/keytool" , when: true }
         - { name: "java_sdk", link: "/usr/lib/jvm/java", path: "{{ java_default_link_src }}"             , when: "{{filecheck and filecheck.stat.exists}}" }
  become: yes
  when: ansible_os_family != "Darwin"
```

**Comment by thokari** [comment]
Not sure is it the same problem?
I got this error:
```
TASK [srsp.oracle-java : alternatives link for "keytool"] ****************************************************************************************************************************************************************************************************************************
fatal: [<hostname>]: FAILED! => {"changed": false, "cmd": "/usr/sbin/update-alternatives --install /usr/bin/keytool java /usr/java/default/bin/keytool 50", "msg": "the primary link for java must be /usr/bin/java", "rc": 2, "stderr": "the primary link for java must be /usr/bin/java\n", "stderr_lines": ["the primary link for java must be /usr/bin/java"], "stdout": "", "stdout_lines": []}
```
Also on the command line:
`[root@<hostname> ~]# /usr/sbin/update-alternatives --install /usr/bin/keytool java /usr/java/default/bin/keytool 50
the primary link for java must be /usr/bin/java`

However I was wondering, why would the `keytool` alternative have the name `java` instead of `keytool`?
Indeed that fixed the problem:
```
- name: alternatives link for "keytool"
   alternatives:
       name: keytool
       link: /usr/bin/keytool
       path: "{{ java_install_dir }}/{{ java_default_link_name }}/bin/keytool"
```
See https://github.com/srsp/ansible-oracle-java/pull/16
