### ISSUE TITLE
JDK 10.0.1 - Variable is not build correctly

### ISSUE THREAD

**Issue by Tux12Fun** [srsp/ansible-oracle-java#14]
Hi,

I'm sorry I found the next "bug"

File: 
Line: 19:

````yaml
- name: set general internal vars for {{ java_version }}
  set_fact:
    # JDK 10 is only available in 10.0.1
    jdk_subversion: 0.1
    jdk_version: "{{ java_version }}.{{ java_subversion }}"
  when: java_version == 10
````

````bash
TASK [srsp.ansible-oracle-java : set general internal vars for 10] *******************************************************************************************
task path: /etc/ansible/roles/srsp.ansible-oracle-java/tasks/set-role-variables.yml:19
ok: [secu1.conrad.local] => {
    "ansible_facts": {
        "jdk_subversion": "0.1",
        "jdk_version": "10."
    },
    "changed": false
}
````

a fix could be
````yaml
- name: set general internal vars for {{ java_version }}
  set_fact:
    # JDK 10 is only available in 10.0.1
    jdk_subversion: 0.1
    jdk_version: "{{ java_version }}.0.1"
  when: java_version == 10
````

Maybe we could build a lookup table as I did it in my last bugreport. With with items and a when statement.
