### ISSUE TITLE
Download java 8 failed

### ISSUE THREAD

**Issue by DO1JLR** [srsp/ansible-oracle-java#32]
Download java 8 failed on Debian buster.
```yml
---
# vars
java_version: 8
```

```yml
TASK [oracle : Download JDK (as tar.gz file)] ******************************************************************************************************************************
fatal: [atlassian-fisheye.wingcon.com]: FAILED! => changed=false 
  dest: /tmp/jdk-8u231-linux-x64.tar.gz
  elapsed: 1
  msg: Request failed
  response: 'HTTP Error 404: Not Found'
  status_code: 404
  url: http://download.oracle.com/otn-pub/java/jdk/8u231-b11/5b13a193868b4bf28bcb45c792fce896/jdk-8u231-linux-x64.tar.gz
```
